# SConscript

Import('env Automatic_Program')
env=env.Copy(warnings_are_errors=0)
Automatic_Program(env,"StephanProblem_CS838",["main.cpp","HermiteInterpolation.cpp","Reinitialize.cpp","Extrapolate.cpp"])


